# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/David/Documents/Work/PRISMS/phaseField

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/David/Documents/Work/PRISMS/phaseField

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/David/Documents/Work/PRISMS/phaseField/CMakeFiles /Users/David/Documents/Work/PRISMS/phaseField/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/David/Documents/Work/PRISMS/phaseField/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named prisms_pf

# Build rule for target.
prisms_pf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prisms_pf
.PHONY : prisms_pf

# fast build rule for target.
prisms_pf/fast:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/build
.PHONY : prisms_pf/fast

#=============================================================================
# Target rules for targets named prisms_pf_debug

# Build rule for target.
prisms_pf_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prisms_pf_debug
.PHONY : prisms_pf_debug

# fast build rule for target.
prisms_pf_debug/fast:
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/build
.PHONY : prisms_pf_debug/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/EquationDependencyParser/EquationDependencyParser.o: src/EquationDependencyParser/EquationDependencyParser.cc.o

.PHONY : src/EquationDependencyParser/EquationDependencyParser.o

# target to build an object file
src/EquationDependencyParser/EquationDependencyParser.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/EquationDependencyParser/EquationDependencyParser.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/EquationDependencyParser/EquationDependencyParser.cc.o
.PHONY : src/EquationDependencyParser/EquationDependencyParser.cc.o

src/EquationDependencyParser/EquationDependencyParser.i: src/EquationDependencyParser/EquationDependencyParser.cc.i

.PHONY : src/EquationDependencyParser/EquationDependencyParser.i

# target to preprocess a source file
src/EquationDependencyParser/EquationDependencyParser.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/EquationDependencyParser/EquationDependencyParser.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/EquationDependencyParser/EquationDependencyParser.cc.i
.PHONY : src/EquationDependencyParser/EquationDependencyParser.cc.i

src/EquationDependencyParser/EquationDependencyParser.s: src/EquationDependencyParser/EquationDependencyParser.cc.s

.PHONY : src/EquationDependencyParser/EquationDependencyParser.s

# target to generate assembly for a file
src/EquationDependencyParser/EquationDependencyParser.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/EquationDependencyParser/EquationDependencyParser.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/EquationDependencyParser/EquationDependencyParser.cc.s
.PHONY : src/EquationDependencyParser/EquationDependencyParser.cc.s

src/FloodFiller/FloodFiller.o: src/FloodFiller/FloodFiller.cc.o

.PHONY : src/FloodFiller/FloodFiller.o

# target to build an object file
src/FloodFiller/FloodFiller.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/FloodFiller/FloodFiller.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/FloodFiller/FloodFiller.cc.o
.PHONY : src/FloodFiller/FloodFiller.cc.o

src/FloodFiller/FloodFiller.i: src/FloodFiller/FloodFiller.cc.i

.PHONY : src/FloodFiller/FloodFiller.i

# target to preprocess a source file
src/FloodFiller/FloodFiller.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/FloodFiller/FloodFiller.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/FloodFiller/FloodFiller.cc.i
.PHONY : src/FloodFiller/FloodFiller.cc.i

src/FloodFiller/FloodFiller.s: src/FloodFiller/FloodFiller.cc.s

.PHONY : src/FloodFiller/FloodFiller.s

# target to generate assembly for a file
src/FloodFiller/FloodFiller.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/FloodFiller/FloodFiller.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/FloodFiller/FloodFiller.cc.s
.PHONY : src/FloodFiller/FloodFiller.cc.s

src/OrderParameterRemapper/OrderParameterRemapper.o: src/OrderParameterRemapper/OrderParameterRemapper.cc.o

.PHONY : src/OrderParameterRemapper/OrderParameterRemapper.o

# target to build an object file
src/OrderParameterRemapper/OrderParameterRemapper.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/OrderParameterRemapper/OrderParameterRemapper.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/OrderParameterRemapper/OrderParameterRemapper.cc.o
.PHONY : src/OrderParameterRemapper/OrderParameterRemapper.cc.o

src/OrderParameterRemapper/OrderParameterRemapper.i: src/OrderParameterRemapper/OrderParameterRemapper.cc.i

.PHONY : src/OrderParameterRemapper/OrderParameterRemapper.i

# target to preprocess a source file
src/OrderParameterRemapper/OrderParameterRemapper.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/OrderParameterRemapper/OrderParameterRemapper.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/OrderParameterRemapper/OrderParameterRemapper.cc.i
.PHONY : src/OrderParameterRemapper/OrderParameterRemapper.cc.i

src/OrderParameterRemapper/OrderParameterRemapper.s: src/OrderParameterRemapper/OrderParameterRemapper.cc.s

.PHONY : src/OrderParameterRemapper/OrderParameterRemapper.s

# target to generate assembly for a file
src/OrderParameterRemapper/OrderParameterRemapper.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/OrderParameterRemapper/OrderParameterRemapper.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/OrderParameterRemapper/OrderParameterRemapper.cc.s
.PHONY : src/OrderParameterRemapper/OrderParameterRemapper.cc.s

src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.o: src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.o

.PHONY : src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.o

# target to build an object file
src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.o
.PHONY : src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.o

src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.i: src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.i

.PHONY : src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.i

# target to preprocess a source file
src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.i
.PHONY : src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.i

src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.s: src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.s

.PHONY : src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.s

# target to generate assembly for a file
src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.s
.PHONY : src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.cc.s

src/SolverParameters/SolverParameters.o: src/SolverParameters/SolverParameters.cc.o

.PHONY : src/SolverParameters/SolverParameters.o

# target to build an object file
src/SolverParameters/SolverParameters.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/SolverParameters/SolverParameters.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/SolverParameters/SolverParameters.cc.o
.PHONY : src/SolverParameters/SolverParameters.cc.o

src/SolverParameters/SolverParameters.i: src/SolverParameters/SolverParameters.cc.i

.PHONY : src/SolverParameters/SolverParameters.i

# target to preprocess a source file
src/SolverParameters/SolverParameters.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/SolverParameters/SolverParameters.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/SolverParameters/SolverParameters.cc.i
.PHONY : src/SolverParameters/SolverParameters.cc.i

src/SolverParameters/SolverParameters.s: src/SolverParameters/SolverParameters.cc.s

.PHONY : src/SolverParameters/SolverParameters.s

# target to generate assembly for a file
src/SolverParameters/SolverParameters.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/SolverParameters/SolverParameters.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/SolverParameters/SolverParameters.cc.s
.PHONY : src/SolverParameters/SolverParameters.cc.s

src/inputFileReader/inputFileReader.o: src/inputFileReader/inputFileReader.cc.o

.PHONY : src/inputFileReader/inputFileReader.o

# target to build an object file
src/inputFileReader/inputFileReader.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/inputFileReader/inputFileReader.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/inputFileReader/inputFileReader.cc.o
.PHONY : src/inputFileReader/inputFileReader.cc.o

src/inputFileReader/inputFileReader.i: src/inputFileReader/inputFileReader.cc.i

.PHONY : src/inputFileReader/inputFileReader.i

# target to preprocess a source file
src/inputFileReader/inputFileReader.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/inputFileReader/inputFileReader.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/inputFileReader/inputFileReader.cc.i
.PHONY : src/inputFileReader/inputFileReader.cc.i

src/inputFileReader/inputFileReader.s: src/inputFileReader/inputFileReader.cc.s

.PHONY : src/inputFileReader/inputFileReader.s

# target to generate assembly for a file
src/inputFileReader/inputFileReader.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/inputFileReader/inputFileReader.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/inputFileReader/inputFileReader.cc.s
.PHONY : src/inputFileReader/inputFileReader.cc.s

src/matrixfree/boundaryConditions.o: src/matrixfree/boundaryConditions.cc.o

.PHONY : src/matrixfree/boundaryConditions.o

# target to build an object file
src/matrixfree/boundaryConditions.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/boundaryConditions.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/boundaryConditions.cc.o
.PHONY : src/matrixfree/boundaryConditions.cc.o

src/matrixfree/boundaryConditions.i: src/matrixfree/boundaryConditions.cc.i

.PHONY : src/matrixfree/boundaryConditions.i

# target to preprocess a source file
src/matrixfree/boundaryConditions.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/boundaryConditions.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/boundaryConditions.cc.i
.PHONY : src/matrixfree/boundaryConditions.cc.i

src/matrixfree/boundaryConditions.s: src/matrixfree/boundaryConditions.cc.s

.PHONY : src/matrixfree/boundaryConditions.s

# target to generate assembly for a file
src/matrixfree/boundaryConditions.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/boundaryConditions.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/boundaryConditions.cc.s
.PHONY : src/matrixfree/boundaryConditions.cc.s

src/matrixfree/buildFields.o: src/matrixfree/buildFields.cc.o

.PHONY : src/matrixfree/buildFields.o

# target to build an object file
src/matrixfree/buildFields.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/buildFields.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/buildFields.cc.o
.PHONY : src/matrixfree/buildFields.cc.o

src/matrixfree/buildFields.i: src/matrixfree/buildFields.cc.i

.PHONY : src/matrixfree/buildFields.i

# target to preprocess a source file
src/matrixfree/buildFields.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/buildFields.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/buildFields.cc.i
.PHONY : src/matrixfree/buildFields.cc.i

src/matrixfree/buildFields.s: src/matrixfree/buildFields.cc.s

.PHONY : src/matrixfree/buildFields.s

# target to generate assembly for a file
src/matrixfree/buildFields.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/buildFields.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/buildFields.cc.s
.PHONY : src/matrixfree/buildFields.cc.s

src/matrixfree/checkpoint.o: src/matrixfree/checkpoint.cc.o

.PHONY : src/matrixfree/checkpoint.o

# target to build an object file
src/matrixfree/checkpoint.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/checkpoint.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/checkpoint.cc.o
.PHONY : src/matrixfree/checkpoint.cc.o

src/matrixfree/checkpoint.i: src/matrixfree/checkpoint.cc.i

.PHONY : src/matrixfree/checkpoint.i

# target to preprocess a source file
src/matrixfree/checkpoint.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/checkpoint.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/checkpoint.cc.i
.PHONY : src/matrixfree/checkpoint.cc.i

src/matrixfree/checkpoint.s: src/matrixfree/checkpoint.cc.s

.PHONY : src/matrixfree/checkpoint.s

# target to generate assembly for a file
src/matrixfree/checkpoint.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/checkpoint.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/checkpoint.cc.s
.PHONY : src/matrixfree/checkpoint.cc.s

src/matrixfree/computeIntegral.o: src/matrixfree/computeIntegral.cc.o

.PHONY : src/matrixfree/computeIntegral.o

# target to build an object file
src/matrixfree/computeIntegral.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeIntegral.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeIntegral.cc.o
.PHONY : src/matrixfree/computeIntegral.cc.o

src/matrixfree/computeIntegral.i: src/matrixfree/computeIntegral.cc.i

.PHONY : src/matrixfree/computeIntegral.i

# target to preprocess a source file
src/matrixfree/computeIntegral.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeIntegral.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeIntegral.cc.i
.PHONY : src/matrixfree/computeIntegral.cc.i

src/matrixfree/computeIntegral.s: src/matrixfree/computeIntegral.cc.s

.PHONY : src/matrixfree/computeIntegral.s

# target to generate assembly for a file
src/matrixfree/computeIntegral.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeIntegral.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeIntegral.cc.s
.PHONY : src/matrixfree/computeIntegral.cc.s

src/matrixfree/computeLHS.o: src/matrixfree/computeLHS.cc.o

.PHONY : src/matrixfree/computeLHS.o

# target to build an object file
src/matrixfree/computeLHS.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeLHS.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeLHS.cc.o
.PHONY : src/matrixfree/computeLHS.cc.o

src/matrixfree/computeLHS.i: src/matrixfree/computeLHS.cc.i

.PHONY : src/matrixfree/computeLHS.i

# target to preprocess a source file
src/matrixfree/computeLHS.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeLHS.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeLHS.cc.i
.PHONY : src/matrixfree/computeLHS.cc.i

src/matrixfree/computeLHS.s: src/matrixfree/computeLHS.cc.s

.PHONY : src/matrixfree/computeLHS.s

# target to generate assembly for a file
src/matrixfree/computeLHS.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeLHS.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeLHS.cc.s
.PHONY : src/matrixfree/computeLHS.cc.s

src/matrixfree/computeRHS.o: src/matrixfree/computeRHS.cc.o

.PHONY : src/matrixfree/computeRHS.o

# target to build an object file
src/matrixfree/computeRHS.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeRHS.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeRHS.cc.o
.PHONY : src/matrixfree/computeRHS.cc.o

src/matrixfree/computeRHS.i: src/matrixfree/computeRHS.cc.i

.PHONY : src/matrixfree/computeRHS.i

# target to preprocess a source file
src/matrixfree/computeRHS.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeRHS.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeRHS.cc.i
.PHONY : src/matrixfree/computeRHS.cc.i

src/matrixfree/computeRHS.s: src/matrixfree/computeRHS.cc.s

.PHONY : src/matrixfree/computeRHS.s

# target to generate assembly for a file
src/matrixfree/computeRHS.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/computeRHS.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/computeRHS.cc.s
.PHONY : src/matrixfree/computeRHS.cc.s

src/matrixfree/init.o: src/matrixfree/init.cc.o

.PHONY : src/matrixfree/init.o

# target to build an object file
src/matrixfree/init.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/init.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/init.cc.o
.PHONY : src/matrixfree/init.cc.o

src/matrixfree/init.i: src/matrixfree/init.cc.i

.PHONY : src/matrixfree/init.i

# target to preprocess a source file
src/matrixfree/init.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/init.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/init.cc.i
.PHONY : src/matrixfree/init.cc.i

src/matrixfree/init.s: src/matrixfree/init.cc.s

.PHONY : src/matrixfree/init.s

# target to generate assembly for a file
src/matrixfree/init.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/init.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/init.cc.s
.PHONY : src/matrixfree/init.cc.s

src/matrixfree/initForTests.o: src/matrixfree/initForTests.cc.o

.PHONY : src/matrixfree/initForTests.o

# target to build an object file
src/matrixfree/initForTests.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/initForTests.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/initForTests.cc.o
.PHONY : src/matrixfree/initForTests.cc.o

src/matrixfree/initForTests.i: src/matrixfree/initForTests.cc.i

.PHONY : src/matrixfree/initForTests.i

# target to preprocess a source file
src/matrixfree/initForTests.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/initForTests.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/initForTests.cc.i
.PHONY : src/matrixfree/initForTests.cc.i

src/matrixfree/initForTests.s: src/matrixfree/initForTests.cc.s

.PHONY : src/matrixfree/initForTests.s

# target to generate assembly for a file
src/matrixfree/initForTests.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/initForTests.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/initForTests.cc.s
.PHONY : src/matrixfree/initForTests.cc.s

src/matrixfree/init_no_ref_NeumannBCs.o: src/matrixfree/init_no_ref_NeumannBCs.cc.o

.PHONY : src/matrixfree/init_no_ref_NeumannBCs.o

# target to build an object file
src/matrixfree/init_no_ref_NeumannBCs.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/init_no_ref_NeumannBCs.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/init_no_ref_NeumannBCs.cc.o
.PHONY : src/matrixfree/init_no_ref_NeumannBCs.cc.o

src/matrixfree/init_no_ref_NeumannBCs.i: src/matrixfree/init_no_ref_NeumannBCs.cc.i

.PHONY : src/matrixfree/init_no_ref_NeumannBCs.i

# target to preprocess a source file
src/matrixfree/init_no_ref_NeumannBCs.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/init_no_ref_NeumannBCs.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/init_no_ref_NeumannBCs.cc.i
.PHONY : src/matrixfree/init_no_ref_NeumannBCs.cc.i

src/matrixfree/init_no_ref_NeumannBCs.s: src/matrixfree/init_no_ref_NeumannBCs.cc.s

.PHONY : src/matrixfree/init_no_ref_NeumannBCs.s

# target to generate assembly for a file
src/matrixfree/init_no_ref_NeumannBCs.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/init_no_ref_NeumannBCs.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/init_no_ref_NeumannBCs.cc.s
.PHONY : src/matrixfree/init_no_ref_NeumannBCs.cc.s

src/matrixfree/initialConditions.o: src/matrixfree/initialConditions.cc.o

.PHONY : src/matrixfree/initialConditions.o

# target to build an object file
src/matrixfree/initialConditions.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/initialConditions.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/initialConditions.cc.o
.PHONY : src/matrixfree/initialConditions.cc.o

src/matrixfree/initialConditions.i: src/matrixfree/initialConditions.cc.i

.PHONY : src/matrixfree/initialConditions.i

# target to preprocess a source file
src/matrixfree/initialConditions.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/initialConditions.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/initialConditions.cc.i
.PHONY : src/matrixfree/initialConditions.cc.i

src/matrixfree/initialConditions.s: src/matrixfree/initialConditions.cc.s

.PHONY : src/matrixfree/initialConditions.s

# target to generate assembly for a file
src/matrixfree/initialConditions.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/initialConditions.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/initialConditions.cc.s
.PHONY : src/matrixfree/initialConditions.cc.s

src/matrixfree/invM.o: src/matrixfree/invM.cc.o

.PHONY : src/matrixfree/invM.o

# target to build an object file
src/matrixfree/invM.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/invM.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/invM.cc.o
.PHONY : src/matrixfree/invM.cc.o

src/matrixfree/invM.i: src/matrixfree/invM.cc.i

.PHONY : src/matrixfree/invM.i

# target to preprocess a source file
src/matrixfree/invM.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/invM.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/invM.cc.i
.PHONY : src/matrixfree/invM.cc.i

src/matrixfree/invM.s: src/matrixfree/invM.cc.s

.PHONY : src/matrixfree/invM.s

# target to generate assembly for a file
src/matrixfree/invM.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/invM.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/invM.cc.s
.PHONY : src/matrixfree/invM.cc.s

src/matrixfree/markBoundaries.o: src/matrixfree/markBoundaries.cc.o

.PHONY : src/matrixfree/markBoundaries.o

# target to build an object file
src/matrixfree/markBoundaries.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/markBoundaries.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/markBoundaries.cc.o
.PHONY : src/matrixfree/markBoundaries.cc.o

src/matrixfree/markBoundaries.i: src/matrixfree/markBoundaries.cc.i

.PHONY : src/matrixfree/markBoundaries.i

# target to preprocess a source file
src/matrixfree/markBoundaries.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/markBoundaries.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/markBoundaries.cc.i
.PHONY : src/matrixfree/markBoundaries.cc.i

src/matrixfree/markBoundaries.s: src/matrixfree/markBoundaries.cc.s

.PHONY : src/matrixfree/markBoundaries.s

# target to generate assembly for a file
src/matrixfree/markBoundaries.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/markBoundaries.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/markBoundaries.cc.s
.PHONY : src/matrixfree/markBoundaries.cc.s

src/matrixfree/matrixFreePDE.o: src/matrixfree/matrixFreePDE.cc.o

.PHONY : src/matrixfree/matrixFreePDE.o

# target to build an object file
src/matrixfree/matrixFreePDE.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/matrixFreePDE.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/matrixFreePDE.cc.o
.PHONY : src/matrixfree/matrixFreePDE.cc.o

src/matrixfree/matrixFreePDE.i: src/matrixfree/matrixFreePDE.cc.i

.PHONY : src/matrixfree/matrixFreePDE.i

# target to preprocess a source file
src/matrixfree/matrixFreePDE.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/matrixFreePDE.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/matrixFreePDE.cc.i
.PHONY : src/matrixfree/matrixFreePDE.cc.i

src/matrixfree/matrixFreePDE.s: src/matrixfree/matrixFreePDE.cc.s

.PHONY : src/matrixfree/matrixFreePDE.s

# target to generate assembly for a file
src/matrixfree/matrixFreePDE.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/matrixFreePDE.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/matrixFreePDE.cc.s
.PHONY : src/matrixfree/matrixFreePDE.cc.s

src/matrixfree/nucleation.o: src/matrixfree/nucleation.cc.o

.PHONY : src/matrixfree/nucleation.o

# target to build an object file
src/matrixfree/nucleation.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/nucleation.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/nucleation.cc.o
.PHONY : src/matrixfree/nucleation.cc.o

src/matrixfree/nucleation.i: src/matrixfree/nucleation.cc.i

.PHONY : src/matrixfree/nucleation.i

# target to preprocess a source file
src/matrixfree/nucleation.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/nucleation.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/nucleation.cc.i
.PHONY : src/matrixfree/nucleation.cc.i

src/matrixfree/nucleation.s: src/matrixfree/nucleation.cc.s

.PHONY : src/matrixfree/nucleation.s

# target to generate assembly for a file
src/matrixfree/nucleation.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/nucleation.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/nucleation.cc.s
.PHONY : src/matrixfree/nucleation.cc.s

src/matrixfree/outputResults.o: src/matrixfree/outputResults.cc.o

.PHONY : src/matrixfree/outputResults.o

# target to build an object file
src/matrixfree/outputResults.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/outputResults.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/outputResults.cc.o
.PHONY : src/matrixfree/outputResults.cc.o

src/matrixfree/outputResults.i: src/matrixfree/outputResults.cc.i

.PHONY : src/matrixfree/outputResults.i

# target to preprocess a source file
src/matrixfree/outputResults.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/outputResults.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/outputResults.cc.i
.PHONY : src/matrixfree/outputResults.cc.i

src/matrixfree/outputResults.s: src/matrixfree/outputResults.cc.s

.PHONY : src/matrixfree/outputResults.s

# target to generate assembly for a file
src/matrixfree/outputResults.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/outputResults.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/outputResults.cc.s
.PHONY : src/matrixfree/outputResults.cc.s

src/matrixfree/postprocessor.o: src/matrixfree/postprocessor.cc.o

.PHONY : src/matrixfree/postprocessor.o

# target to build an object file
src/matrixfree/postprocessor.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/postprocessor.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/postprocessor.cc.o
.PHONY : src/matrixfree/postprocessor.cc.o

src/matrixfree/postprocessor.i: src/matrixfree/postprocessor.cc.i

.PHONY : src/matrixfree/postprocessor.i

# target to preprocess a source file
src/matrixfree/postprocessor.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/postprocessor.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/postprocessor.cc.i
.PHONY : src/matrixfree/postprocessor.cc.i

src/matrixfree/postprocessor.s: src/matrixfree/postprocessor.cc.s

.PHONY : src/matrixfree/postprocessor.s

# target to generate assembly for a file
src/matrixfree/postprocessor.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/postprocessor.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/postprocessor.cc.s
.PHONY : src/matrixfree/postprocessor.cc.s

src/matrixfree/reassignGrains.o: src/matrixfree/reassignGrains.cc.o

.PHONY : src/matrixfree/reassignGrains.o

# target to build an object file
src/matrixfree/reassignGrains.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/reassignGrains.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/reassignGrains.cc.o
.PHONY : src/matrixfree/reassignGrains.cc.o

src/matrixfree/reassignGrains.i: src/matrixfree/reassignGrains.cc.i

.PHONY : src/matrixfree/reassignGrains.i

# target to preprocess a source file
src/matrixfree/reassignGrains.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/reassignGrains.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/reassignGrains.cc.i
.PHONY : src/matrixfree/reassignGrains.cc.i

src/matrixfree/reassignGrains.s: src/matrixfree/reassignGrains.cc.s

.PHONY : src/matrixfree/reassignGrains.s

# target to generate assembly for a file
src/matrixfree/reassignGrains.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/reassignGrains.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/reassignGrains.cc.s
.PHONY : src/matrixfree/reassignGrains.cc.s

src/matrixfree/refine.o: src/matrixfree/refine.cc.o

.PHONY : src/matrixfree/refine.o

# target to build an object file
src/matrixfree/refine.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/refine.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/refine.cc.o
.PHONY : src/matrixfree/refine.cc.o

src/matrixfree/refine.i: src/matrixfree/refine.cc.i

.PHONY : src/matrixfree/refine.i

# target to preprocess a source file
src/matrixfree/refine.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/refine.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/refine.cc.i
.PHONY : src/matrixfree/refine.cc.i

src/matrixfree/refine.s: src/matrixfree/refine.cc.s

.PHONY : src/matrixfree/refine.s

# target to generate assembly for a file
src/matrixfree/refine.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/refine.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/refine.cc.s
.PHONY : src/matrixfree/refine.cc.s

src/matrixfree/reinit.o: src/matrixfree/reinit.cc.o

.PHONY : src/matrixfree/reinit.o

# target to build an object file
src/matrixfree/reinit.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/reinit.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/reinit.cc.o
.PHONY : src/matrixfree/reinit.cc.o

src/matrixfree/reinit.i: src/matrixfree/reinit.cc.i

.PHONY : src/matrixfree/reinit.i

# target to preprocess a source file
src/matrixfree/reinit.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/reinit.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/reinit.cc.i
.PHONY : src/matrixfree/reinit.cc.i

src/matrixfree/reinit.s: src/matrixfree/reinit.cc.s

.PHONY : src/matrixfree/reinit.s

# target to generate assembly for a file
src/matrixfree/reinit.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/reinit.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/reinit.cc.s
.PHONY : src/matrixfree/reinit.cc.s

src/matrixfree/setNonlinearEqInitialGuess.o: src/matrixfree/setNonlinearEqInitialGuess.cc.o

.PHONY : src/matrixfree/setNonlinearEqInitialGuess.o

# target to build an object file
src/matrixfree/setNonlinearEqInitialGuess.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/setNonlinearEqInitialGuess.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/setNonlinearEqInitialGuess.cc.o
.PHONY : src/matrixfree/setNonlinearEqInitialGuess.cc.o

src/matrixfree/setNonlinearEqInitialGuess.i: src/matrixfree/setNonlinearEqInitialGuess.cc.i

.PHONY : src/matrixfree/setNonlinearEqInitialGuess.i

# target to preprocess a source file
src/matrixfree/setNonlinearEqInitialGuess.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/setNonlinearEqInitialGuess.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/setNonlinearEqInitialGuess.cc.i
.PHONY : src/matrixfree/setNonlinearEqInitialGuess.cc.i

src/matrixfree/setNonlinearEqInitialGuess.s: src/matrixfree/setNonlinearEqInitialGuess.cc.s

.PHONY : src/matrixfree/setNonlinearEqInitialGuess.s

# target to generate assembly for a file
src/matrixfree/setNonlinearEqInitialGuess.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/setNonlinearEqInitialGuess.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/setNonlinearEqInitialGuess.cc.s
.PHONY : src/matrixfree/setNonlinearEqInitialGuess.cc.s

src/matrixfree/solve.o: src/matrixfree/solve.cc.o

.PHONY : src/matrixfree/solve.o

# target to build an object file
src/matrixfree/solve.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/solve.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/solve.cc.o
.PHONY : src/matrixfree/solve.cc.o

src/matrixfree/solve.i: src/matrixfree/solve.cc.i

.PHONY : src/matrixfree/solve.i

# target to preprocess a source file
src/matrixfree/solve.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/solve.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/solve.cc.i
.PHONY : src/matrixfree/solve.cc.i

src/matrixfree/solve.s: src/matrixfree/solve.cc.s

.PHONY : src/matrixfree/solve.s

# target to generate assembly for a file
src/matrixfree/solve.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/solve.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/solve.cc.s
.PHONY : src/matrixfree/solve.cc.s

src/matrixfree/solveIncrement.o: src/matrixfree/solveIncrement.cc.o

.PHONY : src/matrixfree/solveIncrement.o

# target to build an object file
src/matrixfree/solveIncrement.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/solveIncrement.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/solveIncrement.cc.o
.PHONY : src/matrixfree/solveIncrement.cc.o

src/matrixfree/solveIncrement.i: src/matrixfree/solveIncrement.cc.i

.PHONY : src/matrixfree/solveIncrement.i

# target to preprocess a source file
src/matrixfree/solveIncrement.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/solveIncrement.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/solveIncrement.cc.i
.PHONY : src/matrixfree/solveIncrement.cc.i

src/matrixfree/solveIncrement.s: src/matrixfree/solveIncrement.cc.s

.PHONY : src/matrixfree/solveIncrement.s

# target to generate assembly for a file
src/matrixfree/solveIncrement.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/solveIncrement.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/solveIncrement.cc.s
.PHONY : src/matrixfree/solveIncrement.cc.s

src/matrixfree/utilities.o: src/matrixfree/utilities.cc.o

.PHONY : src/matrixfree/utilities.o

# target to build an object file
src/matrixfree/utilities.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/utilities.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/utilities.cc.o
.PHONY : src/matrixfree/utilities.cc.o

src/matrixfree/utilities.i: src/matrixfree/utilities.cc.i

.PHONY : src/matrixfree/utilities.i

# target to preprocess a source file
src/matrixfree/utilities.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/utilities.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/utilities.cc.i
.PHONY : src/matrixfree/utilities.cc.i

src/matrixfree/utilities.s: src/matrixfree/utilities.cc.s

.PHONY : src/matrixfree/utilities.s

# target to generate assembly for a file
src/matrixfree/utilities.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/matrixfree/utilities.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/matrixfree/utilities.cc.s
.PHONY : src/matrixfree/utilities.cc.s

src/parallelNucleationList/parallelNucleationList.o: src/parallelNucleationList/parallelNucleationList.cc.o

.PHONY : src/parallelNucleationList/parallelNucleationList.o

# target to build an object file
src/parallelNucleationList/parallelNucleationList.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/parallelNucleationList/parallelNucleationList.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/parallelNucleationList/parallelNucleationList.cc.o
.PHONY : src/parallelNucleationList/parallelNucleationList.cc.o

src/parallelNucleationList/parallelNucleationList.i: src/parallelNucleationList/parallelNucleationList.cc.i

.PHONY : src/parallelNucleationList/parallelNucleationList.i

# target to preprocess a source file
src/parallelNucleationList/parallelNucleationList.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/parallelNucleationList/parallelNucleationList.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/parallelNucleationList/parallelNucleationList.cc.i
.PHONY : src/parallelNucleationList/parallelNucleationList.cc.i

src/parallelNucleationList/parallelNucleationList.s: src/parallelNucleationList/parallelNucleationList.cc.s

.PHONY : src/parallelNucleationList/parallelNucleationList.s

# target to generate assembly for a file
src/parallelNucleationList/parallelNucleationList.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/parallelNucleationList/parallelNucleationList.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/parallelNucleationList/parallelNucleationList.cc.s
.PHONY : src/parallelNucleationList/parallelNucleationList.cc.s

src/userInputParameters/loadVariableAttributes.o: src/userInputParameters/loadVariableAttributes.cc.o

.PHONY : src/userInputParameters/loadVariableAttributes.o

# target to build an object file
src/userInputParameters/loadVariableAttributes.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/loadVariableAttributes.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/loadVariableAttributes.cc.o
.PHONY : src/userInputParameters/loadVariableAttributes.cc.o

src/userInputParameters/loadVariableAttributes.i: src/userInputParameters/loadVariableAttributes.cc.i

.PHONY : src/userInputParameters/loadVariableAttributes.i

# target to preprocess a source file
src/userInputParameters/loadVariableAttributes.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/loadVariableAttributes.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/loadVariableAttributes.cc.i
.PHONY : src/userInputParameters/loadVariableAttributes.cc.i

src/userInputParameters/loadVariableAttributes.s: src/userInputParameters/loadVariableAttributes.cc.s

.PHONY : src/userInputParameters/loadVariableAttributes.s

# target to generate assembly for a file
src/userInputParameters/loadVariableAttributes.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/loadVariableAttributes.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/loadVariableAttributes.cc.s
.PHONY : src/userInputParameters/loadVariableAttributes.cc.s

src/userInputParameters/load_BC_list.o: src/userInputParameters/load_BC_list.cc.o

.PHONY : src/userInputParameters/load_BC_list.o

# target to build an object file
src/userInputParameters/load_BC_list.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/load_BC_list.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/load_BC_list.cc.o
.PHONY : src/userInputParameters/load_BC_list.cc.o

src/userInputParameters/load_BC_list.i: src/userInputParameters/load_BC_list.cc.i

.PHONY : src/userInputParameters/load_BC_list.i

# target to preprocess a source file
src/userInputParameters/load_BC_list.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/load_BC_list.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/load_BC_list.cc.i
.PHONY : src/userInputParameters/load_BC_list.cc.i

src/userInputParameters/load_BC_list.s: src/userInputParameters/load_BC_list.cc.s

.PHONY : src/userInputParameters/load_BC_list.s

# target to generate assembly for a file
src/userInputParameters/load_BC_list.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/load_BC_list.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/load_BC_list.cc.s
.PHONY : src/userInputParameters/load_BC_list.cc.s

src/userInputParameters/load_user_constants.o: src/userInputParameters/load_user_constants.cc.o

.PHONY : src/userInputParameters/load_user_constants.o

# target to build an object file
src/userInputParameters/load_user_constants.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/load_user_constants.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/load_user_constants.cc.o
.PHONY : src/userInputParameters/load_user_constants.cc.o

src/userInputParameters/load_user_constants.i: src/userInputParameters/load_user_constants.cc.i

.PHONY : src/userInputParameters/load_user_constants.i

# target to preprocess a source file
src/userInputParameters/load_user_constants.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/load_user_constants.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/load_user_constants.cc.i
.PHONY : src/userInputParameters/load_user_constants.cc.i

src/userInputParameters/load_user_constants.s: src/userInputParameters/load_user_constants.cc.s

.PHONY : src/userInputParameters/load_user_constants.s

# target to generate assembly for a file
src/userInputParameters/load_user_constants.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/load_user_constants.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/load_user_constants.cc.s
.PHONY : src/userInputParameters/load_user_constants.cc.s

src/userInputParameters/setTimeStepList.o: src/userInputParameters/setTimeStepList.cc.o

.PHONY : src/userInputParameters/setTimeStepList.o

# target to build an object file
src/userInputParameters/setTimeStepList.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/setTimeStepList.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/setTimeStepList.cc.o
.PHONY : src/userInputParameters/setTimeStepList.cc.o

src/userInputParameters/setTimeStepList.i: src/userInputParameters/setTimeStepList.cc.i

.PHONY : src/userInputParameters/setTimeStepList.i

# target to preprocess a source file
src/userInputParameters/setTimeStepList.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/setTimeStepList.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/setTimeStepList.cc.i
.PHONY : src/userInputParameters/setTimeStepList.cc.i

src/userInputParameters/setTimeStepList.s: src/userInputParameters/setTimeStepList.cc.s

.PHONY : src/userInputParameters/setTimeStepList.s

# target to generate assembly for a file
src/userInputParameters/setTimeStepList.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/setTimeStepList.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/setTimeStepList.cc.s
.PHONY : src/userInputParameters/setTimeStepList.cc.s

src/userInputParameters/userInputParameters.o: src/userInputParameters/userInputParameters.cc.o

.PHONY : src/userInputParameters/userInputParameters.o

# target to build an object file
src/userInputParameters/userInputParameters.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/userInputParameters.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/userInputParameters.cc.o
.PHONY : src/userInputParameters/userInputParameters.cc.o

src/userInputParameters/userInputParameters.i: src/userInputParameters/userInputParameters.cc.i

.PHONY : src/userInputParameters/userInputParameters.i

# target to preprocess a source file
src/userInputParameters/userInputParameters.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/userInputParameters.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/userInputParameters.cc.i
.PHONY : src/userInputParameters/userInputParameters.cc.i

src/userInputParameters/userInputParameters.s: src/userInputParameters/userInputParameters.cc.s

.PHONY : src/userInputParameters/userInputParameters.s

# target to generate assembly for a file
src/userInputParameters/userInputParameters.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/userInputParameters/userInputParameters.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/userInputParameters/userInputParameters.cc.s
.PHONY : src/userInputParameters/userInputParameters.cc.s

src/utilities/sortIndexEntryPairList.o: src/utilities/sortIndexEntryPairList.cc.o

.PHONY : src/utilities/sortIndexEntryPairList.o

# target to build an object file
src/utilities/sortIndexEntryPairList.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/utilities/sortIndexEntryPairList.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/utilities/sortIndexEntryPairList.cc.o
.PHONY : src/utilities/sortIndexEntryPairList.cc.o

src/utilities/sortIndexEntryPairList.i: src/utilities/sortIndexEntryPairList.cc.i

.PHONY : src/utilities/sortIndexEntryPairList.i

# target to preprocess a source file
src/utilities/sortIndexEntryPairList.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/utilities/sortIndexEntryPairList.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/utilities/sortIndexEntryPairList.cc.i
.PHONY : src/utilities/sortIndexEntryPairList.cc.i

src/utilities/sortIndexEntryPairList.s: src/utilities/sortIndexEntryPairList.cc.s

.PHONY : src/utilities/sortIndexEntryPairList.s

# target to generate assembly for a file
src/utilities/sortIndexEntryPairList.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/utilities/sortIndexEntryPairList.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/utilities/sortIndexEntryPairList.cc.s
.PHONY : src/utilities/sortIndexEntryPairList.cc.s

src/utilities/vectorBCFunction.o: src/utilities/vectorBCFunction.cc.o

.PHONY : src/utilities/vectorBCFunction.o

# target to build an object file
src/utilities/vectorBCFunction.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/utilities/vectorBCFunction.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/utilities/vectorBCFunction.cc.o
.PHONY : src/utilities/vectorBCFunction.cc.o

src/utilities/vectorBCFunction.i: src/utilities/vectorBCFunction.cc.i

.PHONY : src/utilities/vectorBCFunction.i

# target to preprocess a source file
src/utilities/vectorBCFunction.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/utilities/vectorBCFunction.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/utilities/vectorBCFunction.cc.i
.PHONY : src/utilities/vectorBCFunction.cc.i

src/utilities/vectorBCFunction.s: src/utilities/vectorBCFunction.cc.s

.PHONY : src/utilities/vectorBCFunction.s

# target to generate assembly for a file
src/utilities/vectorBCFunction.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/utilities/vectorBCFunction.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/utilities/vectorBCFunction.cc.s
.PHONY : src/utilities/vectorBCFunction.cc.s

src/variableAttributeLoader/variableAttributeLoader.o: src/variableAttributeLoader/variableAttributeLoader.cc.o

.PHONY : src/variableAttributeLoader/variableAttributeLoader.o

# target to build an object file
src/variableAttributeLoader/variableAttributeLoader.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/variableAttributeLoader/variableAttributeLoader.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/variableAttributeLoader/variableAttributeLoader.cc.o
.PHONY : src/variableAttributeLoader/variableAttributeLoader.cc.o

src/variableAttributeLoader/variableAttributeLoader.i: src/variableAttributeLoader/variableAttributeLoader.cc.i

.PHONY : src/variableAttributeLoader/variableAttributeLoader.i

# target to preprocess a source file
src/variableAttributeLoader/variableAttributeLoader.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/variableAttributeLoader/variableAttributeLoader.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/variableAttributeLoader/variableAttributeLoader.cc.i
.PHONY : src/variableAttributeLoader/variableAttributeLoader.cc.i

src/variableAttributeLoader/variableAttributeLoader.s: src/variableAttributeLoader/variableAttributeLoader.cc.s

.PHONY : src/variableAttributeLoader/variableAttributeLoader.s

# target to generate assembly for a file
src/variableAttributeLoader/variableAttributeLoader.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/variableAttributeLoader/variableAttributeLoader.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/variableAttributeLoader/variableAttributeLoader.cc.s
.PHONY : src/variableAttributeLoader/variableAttributeLoader.cc.s

src/variableContainer/variableContainer.o: src/variableContainer/variableContainer.cc.o

.PHONY : src/variableContainer/variableContainer.o

# target to build an object file
src/variableContainer/variableContainer.cc.o:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/variableContainer/variableContainer.cc.o
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/variableContainer/variableContainer.cc.o
.PHONY : src/variableContainer/variableContainer.cc.o

src/variableContainer/variableContainer.i: src/variableContainer/variableContainer.cc.i

.PHONY : src/variableContainer/variableContainer.i

# target to preprocess a source file
src/variableContainer/variableContainer.cc.i:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/variableContainer/variableContainer.cc.i
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/variableContainer/variableContainer.cc.i
.PHONY : src/variableContainer/variableContainer.cc.i

src/variableContainer/variableContainer.s: src/variableContainer/variableContainer.cc.s

.PHONY : src/variableContainer/variableContainer.s

# target to generate assembly for a file
src/variableContainer/variableContainer.cc.s:
	$(MAKE) -f CMakeFiles/prisms_pf.dir/build.make CMakeFiles/prisms_pf.dir/src/variableContainer/variableContainer.cc.s
	$(MAKE) -f CMakeFiles/prisms_pf_debug.dir/build.make CMakeFiles/prisms_pf_debug.dir/src/variableContainer/variableContainer.cc.s
.PHONY : src/variableContainer/variableContainer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... prisms_pf_debug"
	@echo "... edit_cache"
	@echo "... prisms_pf"
	@echo "... release"
	@echo "... run"
	@echo "... debug"
	@echo "... src/EquationDependencyParser/EquationDependencyParser.o"
	@echo "... src/EquationDependencyParser/EquationDependencyParser.i"
	@echo "... src/EquationDependencyParser/EquationDependencyParser.s"
	@echo "... src/FloodFiller/FloodFiller.o"
	@echo "... src/FloodFiller/FloodFiller.i"
	@echo "... src/FloodFiller/FloodFiller.s"
	@echo "... src/OrderParameterRemapper/OrderParameterRemapper.o"
	@echo "... src/OrderParameterRemapper/OrderParameterRemapper.i"
	@echo "... src/OrderParameterRemapper/OrderParameterRemapper.s"
	@echo "... src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.o"
	@echo "... src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.i"
	@echo "... src/SimplifiedGrainRepresentation/SimplifiedGrainRepresentation.s"
	@echo "... src/SolverParameters/SolverParameters.o"
	@echo "... src/SolverParameters/SolverParameters.i"
	@echo "... src/SolverParameters/SolverParameters.s"
	@echo "... src/inputFileReader/inputFileReader.o"
	@echo "... src/inputFileReader/inputFileReader.i"
	@echo "... src/inputFileReader/inputFileReader.s"
	@echo "... src/matrixfree/boundaryConditions.o"
	@echo "... src/matrixfree/boundaryConditions.i"
	@echo "... src/matrixfree/boundaryConditions.s"
	@echo "... src/matrixfree/buildFields.o"
	@echo "... src/matrixfree/buildFields.i"
	@echo "... src/matrixfree/buildFields.s"
	@echo "... src/matrixfree/checkpoint.o"
	@echo "... src/matrixfree/checkpoint.i"
	@echo "... src/matrixfree/checkpoint.s"
	@echo "... src/matrixfree/computeIntegral.o"
	@echo "... src/matrixfree/computeIntegral.i"
	@echo "... src/matrixfree/computeIntegral.s"
	@echo "... src/matrixfree/computeLHS.o"
	@echo "... src/matrixfree/computeLHS.i"
	@echo "... src/matrixfree/computeLHS.s"
	@echo "... src/matrixfree/computeRHS.o"
	@echo "... src/matrixfree/computeRHS.i"
	@echo "... src/matrixfree/computeRHS.s"
	@echo "... src/matrixfree/init.o"
	@echo "... src/matrixfree/init.i"
	@echo "... src/matrixfree/init.s"
	@echo "... src/matrixfree/initForTests.o"
	@echo "... src/matrixfree/initForTests.i"
	@echo "... src/matrixfree/initForTests.s"
	@echo "... src/matrixfree/init_no_ref_NeumannBCs.o"
	@echo "... src/matrixfree/init_no_ref_NeumannBCs.i"
	@echo "... src/matrixfree/init_no_ref_NeumannBCs.s"
	@echo "... src/matrixfree/initialConditions.o"
	@echo "... src/matrixfree/initialConditions.i"
	@echo "... src/matrixfree/initialConditions.s"
	@echo "... src/matrixfree/invM.o"
	@echo "... src/matrixfree/invM.i"
	@echo "... src/matrixfree/invM.s"
	@echo "... src/matrixfree/markBoundaries.o"
	@echo "... src/matrixfree/markBoundaries.i"
	@echo "... src/matrixfree/markBoundaries.s"
	@echo "... src/matrixfree/matrixFreePDE.o"
	@echo "... src/matrixfree/matrixFreePDE.i"
	@echo "... src/matrixfree/matrixFreePDE.s"
	@echo "... src/matrixfree/nucleation.o"
	@echo "... src/matrixfree/nucleation.i"
	@echo "... src/matrixfree/nucleation.s"
	@echo "... src/matrixfree/outputResults.o"
	@echo "... src/matrixfree/outputResults.i"
	@echo "... src/matrixfree/outputResults.s"
	@echo "... src/matrixfree/postprocessor.o"
	@echo "... src/matrixfree/postprocessor.i"
	@echo "... src/matrixfree/postprocessor.s"
	@echo "... src/matrixfree/reassignGrains.o"
	@echo "... src/matrixfree/reassignGrains.i"
	@echo "... src/matrixfree/reassignGrains.s"
	@echo "... src/matrixfree/refine.o"
	@echo "... src/matrixfree/refine.i"
	@echo "... src/matrixfree/refine.s"
	@echo "... src/matrixfree/reinit.o"
	@echo "... src/matrixfree/reinit.i"
	@echo "... src/matrixfree/reinit.s"
	@echo "... src/matrixfree/setNonlinearEqInitialGuess.o"
	@echo "... src/matrixfree/setNonlinearEqInitialGuess.i"
	@echo "... src/matrixfree/setNonlinearEqInitialGuess.s"
	@echo "... src/matrixfree/solve.o"
	@echo "... src/matrixfree/solve.i"
	@echo "... src/matrixfree/solve.s"
	@echo "... src/matrixfree/solveIncrement.o"
	@echo "... src/matrixfree/solveIncrement.i"
	@echo "... src/matrixfree/solveIncrement.s"
	@echo "... src/matrixfree/utilities.o"
	@echo "... src/matrixfree/utilities.i"
	@echo "... src/matrixfree/utilities.s"
	@echo "... src/parallelNucleationList/parallelNucleationList.o"
	@echo "... src/parallelNucleationList/parallelNucleationList.i"
	@echo "... src/parallelNucleationList/parallelNucleationList.s"
	@echo "... src/userInputParameters/loadVariableAttributes.o"
	@echo "... src/userInputParameters/loadVariableAttributes.i"
	@echo "... src/userInputParameters/loadVariableAttributes.s"
	@echo "... src/userInputParameters/load_BC_list.o"
	@echo "... src/userInputParameters/load_BC_list.i"
	@echo "... src/userInputParameters/load_BC_list.s"
	@echo "... src/userInputParameters/load_user_constants.o"
	@echo "... src/userInputParameters/load_user_constants.i"
	@echo "... src/userInputParameters/load_user_constants.s"
	@echo "... src/userInputParameters/setTimeStepList.o"
	@echo "... src/userInputParameters/setTimeStepList.i"
	@echo "... src/userInputParameters/setTimeStepList.s"
	@echo "... src/userInputParameters/userInputParameters.o"
	@echo "... src/userInputParameters/userInputParameters.i"
	@echo "... src/userInputParameters/userInputParameters.s"
	@echo "... src/utilities/sortIndexEntryPairList.o"
	@echo "... src/utilities/sortIndexEntryPairList.i"
	@echo "... src/utilities/sortIndexEntryPairList.s"
	@echo "... src/utilities/vectorBCFunction.o"
	@echo "... src/utilities/vectorBCFunction.i"
	@echo "... src/utilities/vectorBCFunction.s"
	@echo "... src/variableAttributeLoader/variableAttributeLoader.o"
	@echo "... src/variableAttributeLoader/variableAttributeLoader.i"
	@echo "... src/variableAttributeLoader/variableAttributeLoader.s"
	@echo "... src/variableContainer/variableContainer.o"
	@echo "... src/variableContainer/variableContainer.i"
	@echo "... src/variableContainer/variableContainer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

